// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMyweuhejhsAc2DYY5_HQF54E6wr0Xhds',
    appId: '1:397710161832:web:dc6c96e244065658238f9d',
    messagingSenderId: '397710161832',
    projectId: 'test-83027',
    authDomain: 'test-83027.firebaseapp.com',
    storageBucket: 'test-83027.firebasestorage.app',
    measurementId: 'G-1VS0T8FLCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdsDUdfGUDB2mulE7SctN5j20le1mwRHk',
    appId: '1:397710161832:android:24665ede535bb3a8238f9d',
    messagingSenderId: '397710161832',
    projectId: 'test-83027',
    storageBucket: 'test-83027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOiXDVAd8fb-WT_dILyiSHLbiXgXbD7RY',
    appId: '1:397710161832:ios:d97a0b3347d59017238f9d',
    messagingSenderId: '397710161832',
    projectId: 'test-83027',
    storageBucket: 'test-83027.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOiXDVAd8fb-WT_dILyiSHLbiXgXbD7RY',
    appId: '1:397710161832:ios:d97a0b3347d59017238f9d',
    messagingSenderId: '397710161832',
    projectId: 'test-83027',
    storageBucket: 'test-83027.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEQxNYdKPwkIWz2RShkQyouXMdIrXvObo',
    appId: '1:397710161832:web:93cfb72a136e3ef2238f9d',
    messagingSenderId: '397710161832',
    projectId: 'test-83027',
    authDomain: 'test-83027.firebaseapp.com',
    storageBucket: 'test-83027.firebasestorage.app',
    measurementId: 'G-4WHX0L0S0R',
  );
}
